### ISSUE TITLE
Some functions in api.utils are not functions

### ISSUE THREAD

**Issue by hueneburg** [evantahler/actionhero#693]
After multiple times deleting and reinstalling node_modules I still get the error that some functions in api.utils are not functions.
I noticed two functions so far, that are apparently not as functions defined: api.utils.padDateDoubleStr and api.utils.hashLength

My package.json.depencies: 
```javascript
{
    "actionhero": "latest",
    "grunt": "latest",
    "mongoose": "^4.1.11",
    "ws": "latest"
  }
```

**Comment by evantahler** [comment]
You can see those functions defined here: https://github.com/evantahler/actionhero/blob/master/initializers/utils.js

Can you give more context to your errors?  A stack trace?  A reproducible error example?

**Comment by hueneburg** [comment]
here is a stacktrace for the api.utils.padDateDoubleStr is not a function exception:

´´´
npm start                                                                               ] 13:58:30 

> my_actionhero_project@0.0.1 start /home/armin/arbeit/SitHandler
> actionhero start

info: actionhero >> start
2015-10-27 13:58:36 - notice: *** starting actionhero ***
2015-10-27 13:58:36 - warning: running with fakeredis
/home/armin/arbeit/SitHandler/node_modules/actionhero/initializers/utils.js:15
        api.utils.padDateDoubleStr(time.getFullYear()) +
                  ^

TypeError: api.utils.padDateDoubleStr is not a function
    at api.utils.sqlDateTime (/home/armin/arbeit/SitHandler/node_modules/actionhero/initializers/utils.js:15:19)
    at Object.exports.log (/home/armin/arbeit/SitHandler/node_modules/winston/lib/winston/common.js:132:41)
    at Console.log (/home/armin/arbeit/SitHandler/node_modules/winston/lib/winston/transports/console.js:97:19)
    at emit (/home/armin/arbeit/SitHandler/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/armin/arbeit/SitHandler/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/armin/arbeit/SitHandler/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/armin/arbeit/SitHandler/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/home/armin/arbeit/SitHandler/node_modules/winston/lib/winston/logger.js:214:9)
    at Object.api.log (/home/armin/arbeit/SitHandler/node_modules/actionhero/initializers/logger.js:54:22)
    at Object.module.exports.start (/home/armin/arbeit/SitHandler/node_modules/actionhero/initializers/pids.js:48:9)
´´´

**Comment by hueneburg** [comment]
ok, found the error. i had an initializer with the name utils. that seems to mess up the other utils object in the api.
