### ISSUE TITLE
Live reloading of changed Config fails

### ISSUE THREAD

**Issue by S3bb1** [evantahler/actionhero#780]
When hot reloading changed Configs, ActionHero crashes with error message : 

```
2016-02-23T18:32:43.553Z - info:  0=*** rebooting due to config change (%s) ***, 1=/project/api/config/sequelize.js
/project/api/node_modules/actionhero/initializers/config.js:96
      api.commands.restart.call(api._self);
                  ^

TypeError: Cannot read property 'restart' of undefined
    at rebootCallback (/project/api/node_modules/actionhero/initializers/config.js:96:19)
    at /project/api/node_modules/actionhero/initializers/config.js:27:15
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13) 
```

This issue comes from the line https://github.com/evantahler/actionhero/blob/master/initializers/config.js#L19

It seems that watchFile does strange things with the current scope. 

When the watchFile is replaced with fs.watch, all works fine.
```
fs.watchFile(file, function(event, filename){
          if(event === 'change' && api.config.general.developmentMode === true){
```

Found a note in the Node.JS wiki:

> Note: fs.watch() is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

**Comment by evantahler** [comment]
I can't reproduce this at all.  I can tell that you are using an older version of node here because the string interpolation isn't working.  Can you try again on node 4+ with the latest version of actionhero?

```
2016-02-24T18:18:28.562Z - info: actionhero >> start
2016-02-24T18:18:28.656Z - notice: *** starting actionhero ***
2016-02-24T18:18:28.713Z - warning: running with fakeredis
2016-02-24T18:18:28.724Z - info: actionhero member 192.168.80.162 has joined the cluster
2016-02-24T18:18:28.846Z - notice: pid: 90064
2016-02-24T18:18:28.847Z - notice: server ID: 192.168.80.162
2016-02-24T18:18:28.857Z - notice: Starting server: web
2016-02-24T18:18:28.865Z - notice: Starting server: websocket
2016-02-24T18:18:29.460Z - notice: environment: development
2016-02-24T18:18:29.461Z - notice: *** Server Started ***

2016-02-24T18:18:31.855Z - info: *** Rebooting due to initializer change (/Users/evantahler/Dropbox/Desktop/actionhero_tmp/initializers/test.js) ***

2016-02-24T18:18:31.856Z - alert: Shutting down open servers and stopping task processing...
2016-02-24T18:18:31.858Z - notice: Stopping server: web
2016-02-24T18:18:31.859Z - notice: Stopping server: websocket
2016-02-24T18:18:31.864Z - alert: The actionhero has been stopped
2016-02-24T18:18:31.866Z - info: actionhero member 192.168.80.162 has left the cluster
2016-02-24T18:18:31.909Z - notice: *** starting actionhero ***
2016-02-24T18:18:31.913Z - warning: running with fakeredis
2016-02-24T18:18:31.916Z - info: actionhero member 192.168.80.162 has joined the cluster
2016-02-24T18:18:31.933Z - notice: pid: 90064
2016-02-24T18:18:31.933Z - notice: server ID: 192.168.80.162
2016-02-24T18:18:31.939Z - notice: Starting server: web
2016-02-24T18:18:31.940Z - notice: Starting server: websocket
2016-02-24T18:18:32.309Z - notice: environment: development
2016-02-24T18:18:32.310Z - notice: *** Server Started ***
2016-02-24T18:18:32.311Z - info: *** actionhero restarted ***
```

**Comment by S3bb1** [comment]
Sure:

```
C:\Users\Sebastian\Documents\GitHub\actionhero>node --version
v4.3.1

C:\Users\Sebastian\Documents\GitHub\actionhero>npm start

> actionhero@13.0.4 start C:\Users\Sebastian\Documents\GitHub\actionhero
> node ./bin/actionhero

2016-02-24T19:25:21.964Z - info: actionhero >> start
2016-02-24T19:25:22.044Z - notice: *** starting actionhero ***
2016-02-24T19:25:22.070Z - warning: running with fakeredis
2016-02-24T19:25:22.081Z - info: actionhero member 192.168.178.21 has joined the
 cluster
2016-02-24T19:25:22.256Z - notice: pid: 16084
2016-02-24T19:25:22.257Z - notice: server ID: 192.168.178.21
2016-02-24T19:25:22.258Z - info: ensuring the existence of the chatRoom: default
Room
2016-02-24T19:25:22.259Z - info: ensuring the existence of the chatRoom: another
Room
2016-02-24T19:25:22.268Z - info: resque scheduler started
2016-02-24T19:25:22.271Z - notice: Starting server: web
2016-02-24T19:25:22.278Z - notice: Starting server: websocket
2016-02-24T19:25:22.731Z - notice: environment: development
2016-02-24T19:25:22.732Z - info: init dashboard functionalities
2016-02-24T19:25:22.735Z - info: init session handling
2016-02-24T19:25:22.738Z - info: init session handling
2016-02-24T19:25:22.740Z - notice: *** Server Started ***
2016-02-24T19:25:22.743Z - info: created admin user
2016-02-24T19:25:22.785Z - info: worker: started workerId=1
2016-02-24T19:25:23.422Z - info: worker: started workerId=2
2016-02-24T19:25:26.776Z - info:  0=*** rebooting due to config change (%s) ***,
 1=C:\Users\Sebastian\Documents\GitHub\actionhero\config\api.js
C:\Users\Sebastian\Documents\GitHub\actionhero\initializers\config.js:96
      api.commands.restart.call(api._self);
                  ^

TypeError: Cannot read property 'restart' of undefined
    at rebootCallback (C:\Users\Sebastian\Documents\GitHub\actionhero\initialize
rs\config.js:96:19)
    at C:\Users\Sebastian\Documents\GitHub\actionhero\initializers\config.js:27:
15
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! actionhero@13.0.4 start: `node ./bin/actionhero`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the actionhero@13.0.4 start script 'node ./bin/actionhero'.
npm ERR! This is most likely a problem with the actionhero package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/actionhero
npm ERR! You can get their info via:
npm ERR!     npm owner ls actionhero
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sebastian\Documents\GitHub\actionhero\npm-debug.log

C:\Users\Sebastian\Documents\GitHub\actionhero>
```

**Comment by S3bb1** [comment]
and with 13.1:

```
C:\Users\Sebastian\Documents\GitHub\actionhero>npm start

> actionhero@13.1.0 start C:\Users\Sebastian\Documents\GitHub\actionhero
> node ./bin/actionhero

2016-02-24T19:28:22.598Z - info: actionhero >> start
2016-02-24T19:28:22.674Z - notice: *** starting actionhero ***
2016-02-24T19:28:22.702Z - warning: running with fakeredis
2016-02-24T19:28:22.710Z - info: actionhero member 192.168.178.21 has joined the
 cluster
2016-02-24T19:28:22.838Z - notice: pid: 16536
2016-02-24T19:28:22.839Z - notice: server ID: 192.168.178.21
2016-02-24T19:28:22.845Z - notice: Starting server: web
2016-02-24T19:28:22.853Z - notice: Starting server: websocket
2016-02-24T19:28:23.288Z - notice: environment: development
2016-02-24T19:28:23.289Z - notice: *** Server Started ***
2016-02-24T19:28:28.416Z - info:  0=*** rebooting due to config change (%s) ***,
 1=C:\Users\Sebastian\Documents\GitHub\actionhero\config\api.js
C:\Users\Sebastian\Documents\GitHub\actionhero\initializers\config.js:96
      api.commands.restart.call(api._self);
                  ^

TypeError: Cannot read property 'restart' of undefined
    at rebootCallback (C:\Users\Sebastian\Documents\GitHub\actionhero\initialize
rs\config.js:96:19)
    at C:\Users\Sebastian\Documents\GitHub\actionhero\initializers\config.js:27:
15
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! actionhero@13.1.0 start: `node ./bin/actionhero`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the actionhero@13.1.0 start script 'node ./bin/actionhero'.
npm ERR! This is most likely a problem with the actionhero package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/actionhero
npm ERR! You can get their info via:
npm ERR!     npm owner ls actionhero
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sebastian\Documents\GitHub\actionhero\npm-debug.log

C:\Users\Sebastian\Documents\GitHub\actionhero>
```

**Comment by S3bb1** [comment]
@evantahler 

can you try changing a config file ? ... you've changed an initializer. This works!

**Comment by evantahler** [comment]
Ahh! I missed that it was a config file changing and not an initializer. On it.

**Comment by neilstuartcraig** [comment]
FWIW - i see this issue (on node v5) too. Happy to help if needed.

**Comment by evantahler** [comment]
Got a fix here => https://github.com/evantahler/actionhero/pull/783
