### ISSUE TITLE
Testing using `should.be` throws is not a function

### ISSUE THREAD

**Issue by running-coder** [evantahler/actionhero#796]
hey there,

I was writing for test for an api requests and had this error.

``` javascript
// My test
it('test for create contact action', function (done) {
    api.specHelper.runAction(
        'createContact',
        {
            'userId': '42',
            'name': 'test name',
            'jobTitle': 'test jobTitle',
            'address': 'test address',
            'phoneNumbers': 'test phoneNumbers',
            'email': 'test email',
            'picture': 'test picture'
        },
        function (response) {

            console.log('~~~~~~')
            console.log(response)
            console.log('~~~~~~')

            response.status.should.equal(true);
            response.data.should.be.an.instanceOf(Object);

            done();
        }
    );
});
```

``` javascript
// the console.log(response) outputs

{ status: true,
  data:
   { userId: 42,
     contactId: 1,
     name: 'test name',
     jobTitle: 'test jobTitle',
     address: 'test address',
     phoneNumbers: 'test phoneNumbers',
     email: 'test email',
     picture: 'test picture',
     status: 1,
     createdAt: 1458411532618,
     updatedAt: 1458411532618 },
  messageCount: 1,
  serverInformation: { serverName: 'Contacts API', apiVersion: '0.0.1' },
  requesterInformation:
   { id: 'f1726758-2c64-492c-80f8-159ab574fe67',
     remoteIP: 'testServer',
     receivedParams:
      { userId: 42,
        name: 'test name',
        jobTitle: 'test jobTitle',
        address: 'test address',
        phoneNumbers: 'test phoneNumbers',
        email: 'test email',
        picture: 'test picture',
        action: 'createContact',
        apiVersion: 'v1' } } }
```

``` javascript
// The error
   1) test for create contact action


  2 passing (1s)
  1 failing

  1) Contacts Tests test for create contact action:
     Uncaught TypeError: response.data.userId.should.be is not a function
      at Object.<anonymous> (C:\Ionic\contactapp\api\test\contacts.js:56:41)
      at C:\Ionic\contactapp\api\node_modules\actionhero\initializers\specHelper.js:39:55



npm ERR! Test failed.  See above for more details.
```

I am using the [should chaining assertions example](https://www.npmjs.com/package/should#chaining-assertions).

Any idea? (I am using the latest version, just re-installed a fresh instance yesterday)

Thanks

**Comment by evantahler** [comment]
Did you `var should = require('should')` anywhere in that file?  I often forget that...

**Comment by running-coder** [comment]
oh just found out 10 seconds after creating the ticket, my mistake... perhaps i should correctly read the error message :)

**Comment by running-coder** [comment]
was using:
`response.data.userId.should.be('42');`
instead of:
`response.data.userId.should.equal(42);`

**Comment by l0oky** [comment]
Nice nickname :D
