### ISSUE TITLE
Copying servers configs fails on plugin link

### ISSUE THREAD

**Issue by SDSWanderer** [evantahler/actionhero#807]
Hi! I've trying to write my own server, and publish it as an npm module. The default config files of the plugin must be automatically copied from the config folder of my plugin to a proper directory of the user app. When user runs an `npm run action hero link -- --name ah-awesome-server` command, it works fine, until I place my config to a `servers` subdirectory. Then, I've got next error:
 
```
➜  test-app git:(master) ✗ npm run actionhero link -- --name ah-awesome-server

> my_actionhero_project@0.0.1 actionhero /home/dan/DEV/ah-awesome-server/test-app
> actionhero "link" "--name" "ah-awesome-server"

2016-04-03T20:28:55.642Z - info: actionhero >> link
2016-04-03T20:28:55.646Z - info: linking the plugin found at node_modules/ah-awesome-server
2016-04-03T20:28:55.647Z - alert:  - directory '/home/dan/DEV/ah-qwesome-server/test-app/servers/plugins' already exists, skipping
2016-04-03T20:28:55.647Z - alert:  - link file '/home/dan/DEV/ah-qwesome-server/test-app/servers/plugins/ah-qwesome-server.link' already exists, skipping
fs.js:651
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at /home/dan/DEV/ah-qwesome-server/test-app/node_modules/actionhero/bin/methods/link.js:49:24
    at Array.forEach (native)
    at Object.exports.link (/home/dan/DEV/ah-qwesome-server/test-app/node_modules/actionhero/bin/methods/link.js:48:37)
    at run (/home/dan/DEV/ah-qwesome-server/test-app/node_modules/actionhero/bin/actionhero:194:40)
    at /home/dan/DEV/ah-qwesome-server/test-app/node_modules/actionhero/bin/actionhero:215:7
    at _combinedTickCallback (node.js:376:9)
    at process._tickDomainCallback (node.js:431:11)

```

**Comment by evantahler** [comment]
great catch! 
Can you try [this branch](https://github.com/evantahler/actionhero/pull/808) out and confirm that it solves the problem?

**Comment by SDSWanderer** [comment]
Yes, it works fine, thanks!

**Comment by evantahler** [comment]
v13.3.1 is now up on NPM with this change
