### ISSUE TITLE
(Windows 10 - Node v6.2.2 - NPM v3.9.6) Crash on get http://127.0.0.1:8080/

### ISSUE THREAD

**Issue by FavreNicolas** [evantahler/actionhero#879]
Hello,

On fresh install.

My server crash on get http://127.0.0.1:8080/ 
So when I go on http://127.0.0.1:8080/api/status it works

Console output \/
```
C:\Users\nicolas\Debans\api  (debans_gaming_api@0.0.1)
λ npm start

> debans_gaming_api@0.0.1 start C:\Users\nicolas\Debans\api
> actionhero start

2016-06-22T21:54:36.318Z - info: actionhero >> start
2016-06-22T21:54:36.754Z - notice: *** starting actionhero ***
2016-06-22T21:54:36.927Z - warning: running with fakeredis
2016-06-22T21:54:36.967Z - info: actionhero member 192.168.1.68 has joined the cluster
2016-06-22T21:54:37.397Z - notice: pid: 10116
2016-06-22T21:54:37.402Z - notice: server ID: 192.168.1.68
2016-06-22T21:54:37.444Z - notice: Starting server: `web` @ 0.0.0.0:8080
2016-06-22T21:54:37.490Z - notice: Starting server: `websocket`
2016-06-22T21:54:40.865Z - notice: environment: development
_http_outgoing.js:309
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:309:11)
    at ServerResponse.OutgoingMessage._storeHeader (_http_outgoing.js:223:9)
    at ServerResponse.writeHead (_http_server.js:218:8)
    at server.sendWithCompression (C:\Users\nicolas\Debans\api\node_modules\actionhero\servers\web.js:194:38)
    at server.sendFile (C:\Users\nicolas\Debans\api\node_modules\actionhero\servers\web.js:148:14)
    at C:\Users\nicolas\Debans\api\node_modules\actionhero\initializers\genericServer.js:99:14
    at ReadStream.<anonymous> (C:\Users\nicolas\Debans\api\node_modules\actionhero\initializers\staticFile.js:73:15)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at fs.js:1718:10

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nicolas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! debans_gaming_api@0.0.1 start: `actionhero start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the debans_gaming_api@0.0.1 start script 'actionhero start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the debans_gaming_api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     actionhero start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs debans_gaming_api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls debans_gaming_api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nicolas\Debans\api\npm-debug.log
```

**Comment by evantahler** [comment]
can you share specifically what the steps for `On fresh install` are?  Thanks!

**Comment by FavreNicolas** [comment]
I just install with "./node_modules/.bin/actionhero generate"

**Comment by FavreNicolas** [comment]
And run for test !

**Comment by evantahler** [comment]
man... developing on windows sucks.  I'm as far as https://github.com/coreybutler/nvm-windows

**Comment by FavreNicolas** [comment]
Which version I use ?

**Comment by evantahler** [comment]
first, on windows the generate command would be `./node_modules/.bin/actionhero.cmd generate`

**Comment by evantahler** [comment]
other than that, it works fine for me

```
Evan Tahler@WIN-JB35ERASRRD MINGW64 ~/Desktop/test
$ node --version
v6.2.2

Evan Tahler@WIN-JB35ERASRRD MINGW64 ~/Desktop/test
$ npm --version
3.9.5
```

**Comment by FavreNicolas** [comment]
Not work, swit project to ubuntu !

**Comment by l0oky** [comment]
Nevertheless, this shouldn't crash on Windows...

**Comment by evantahler** [comment]
Can anyone else reproduce this?  If we can't reproduce it, it's not a real bug :/

**Comment by yinwz** [comment]
me too, crash on  http://127.0.0.1:8080/ 
OS: win10_x64
node:4.4.5
npm:2.15.5

the error log is:
D:\yinwz\Desktop\node>npm start

> my_actionhero_project@0.0.1 start D:\yinwz\Desktop\node
> actionhero start

2016-06-30T08:42:07.145Z - info: actionhero >> start
2016-06-30T08:42:07.261Z - notice: *** starting actionhero ***
2016-06-30T08:42:07.277Z - info: Redis connection `client` connected
2016-06-30T08:42:07.277Z - info: Redis connection `subscriber` connected
2016-06-30T08:42:07.277Z - info: Redis connection `tasks` connected
2016-06-30T08:42:07.293Z - info: actionhero member 192.168.10.69 has joined the cluster
2016-06-30T08:42:07.428Z - notice: pid: 3576
2016-06-30T08:42:07.428Z - notice: server ID: 192.168.10.69
2016-06-30T08:42:07.461Z - notice: Starting server: `web` @ 0.0.0.0:8080
2016-06-30T08:42:07.461Z - notice: Starting server: `websocket`
2016-06-30T08:42:08.079Z - notice: environment: development
2016-06-30T08:42:08.079Z - notice: *** Server Started ***
_http_outgoing.js:309
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:309:13)
    at ServerResponse.OutgoingMessage._storeHeader (_http_outgoing.js:222:9)
    at ServerResponse.writeHead (_http_server.js:218:8)
    at server.sendWithCompression (D:\yinwz\Desktop\node\node_modules\actionhero\servers\web.js:194:38)
    at server.sendFile (D:\yinwz\Desktop\node\node_modules\actionhero\servers\web.js:148:14)
    at D:\yinwz\Desktop\node\node_modules\actionhero\initializers\genericServer.js:99:14
    at ReadStream.<anonymous> (D:\yinwz\Desktop\node\node_modules\actionhero\initializers\staticFile.js:73:15)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at fs.js:1683:10

npm ERR! Windows_NT 10.0.14366
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! my_actionhero_project@0.0.1 start: `actionhero start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my_actionhero_project@0.0.1 start script 'actionhero start'.
npm ERR! This is most likely a problem with the my_actionhero_project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     actionhero start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my_actionhero_project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls my_actionhero_project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\yinwz\Desktop\node\npm-debug.log

D:\yinwz\Desktop\node>

**Comment by yinwz** [comment]
look this url
http://www.alexkras.com/typeerror-the-header-content-contains-invalid-characters/?utm_source=tuicool&utm_medium=referral

**Comment by yinwz** [comment]
node_modules\actionhero\servers\web.js
line 110
`if(lastModified){ connection.rawConnection.responseHeaders.push(['Last-Modified', new Date(lastModified)]); }`
modify to
`if(lastModified){ connection.rawConnection.responseHeaders.push(['Last-Modified', new Date(lastModified).toUTCString()]); }`

**Comment by evantahler** [comment]
That is great detective work! 
I'll guess that your default locale involves reporting dates in a non-english / non-western way?

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/pull/884

**Comment by evantahler** [comment]
https://github.com/evantahler/actionhero/releases/tag/v14.0.3 released to address this!

**Comment by yinwz** [comment]
> I'll guess that your default locale involves reporting dates in a non-english / non-western way?

Yes, one fifth of population are Chinese

**Comment by evantahler** [comment]
All fixed!
