### ISSUE TITLE
error after updating to 14.0.11 -> TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by MarcusSpecht** [evantahler/actionhero#906]
# TypeError: Cannot read property 'match' of undefined

- ActionHero Version: `14.0.11`
- Node.js Version: `6.3.1`
- nmp Version '3.10.5'
- Operating System `Windows 10 aka Windows_NT 10.0.10586`

# Steps to reproduce your error
- update actionhero to 14.0.11 on Win 10 (mine was 13.4.4 before)
- npm start

# Stacktrace
```
TypeError: Cannot read property 'match' of undefined
    at RedisClient.return_error (\node_modules\redis\index.js:601:28)
    at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnError (\node_modules\redis\index.js:151:18)
    at Object.api.utils.hashMerge (\node_modules\actionhero\initializers\utils.js:41:28)
    at Object.api.utils.hashMerge (\node_modules\actionhero\initializers\utils.js:38:28)
    at Object.api.utils.hashMerge (\node_modules\actionhero\initializers\utils.js:43:32)
    at Object.api.utils.hashMerge (\node_modules\actionhero\initializers\utils.js:22:28)
    at Object.api.utils.hashMerge (\node_modules\actionhero\initializers\utils.js:43:32)
    at api.loadConfigDirectory (\node_modules\actionhero\initializers\config.js:120:63)
    at Array.map (native)
    at Object.module.exports.initialize (\node_modules\actionhero\initializers\config.js:169:17)

\node_modules\actionhero\bin\actionhero:222
      throw e;
      ^

Error: Unable to load configurations, errors: {\\config\\redis.js":{"msg":"TypeError: Cannot read property 'match' of undefined"}}
    at api.loadConfigDirectory (\node_modules\actionhero\initializers\config.js:138:19)
    at Array.map (native)
    at Object.module.exports.initialize (\node_modules\actionhero\initializers\config.js:169:17)
    at \node_modules\actionhero\bin\actionhero:211:18
    at Object.module.exports.initialize (\node_modules\actionhero\initializers\utils.js:278:5)
    at Object.<anonymous> (\node_modules\actionhero\bin\actionhero:209:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by evantahler** [comment]
Thank you for the great bug report! 

Have you re-configured your `/config/redis.js`?  There have been drastic (breaking) changes to how redis is to be configured now: https://github.com/evantahler/actionhero/blob/master/config/redis.js

**Comment by MarcusSpecht** [comment]
Seems like i use an old config/redis.js file
```
exports['default'] = {
  redis: function(api){
    var redisDetails = {
      // Which channel to use on redis pub/sub for RPC communication
      channel: 'actionhero',
      // How long to wait for an RPC call before considering it a failure
      rpcTimeout: 5000,
      // which redis package should you ise?
      pkg: 'fakeredis',

      // Basic configuration options
      host     : process.env.REDIS_HOST || '127.0.0.1',
      port     : process.env.REDIS_PORT || 6379,
      database : process.env.REDIS_DB   || 0,
    };
    ...
```
Those don't get updated by default using npm update!? I can see why. What is the best way to update actionhero config files while still maintaining customizations?

**Comment by evantahler** [comment]
> Those don't get updated by default using npm update!?

Absolutely not! We have no way of knowing what custom magic you've included in there, and simply overwriting it would be a pretty developer experience.  Even if you are using a configuration *close* to the default, it would be hard to diff/statically analyze any differences. 

Copy in a new config from either the master branch or a newly generated actionhero project and manually re-apply your changes.  There is no programatic way to do so.

**Comment by evantahler** [comment]
We also are well aware that we should be writing `upgrade guides` between major versions :/

**Comment by neilstuartcraig** [comment]
Apologies for the interjection but it occurs to me that it'd be perhaps useful to ask for e.g. A markdown file with each PR stating impact on updates. Something along those lines at least seems sensible? Any takers?

**Comment by evantahler** [comment]
We are talking about this very thing right now in the slack channel!

**Comment by evantahler** [comment]
All that is formally written down are the release notes, which tend to at least note breaking changes, IE: https://github.com/evantahler/actionhero/releases/tag/v14.0.0

**Comment by MarcusSpecht** [comment]
Thx I will update my files manually. I am a newb to nodejs so I was looking for a convenient but awesome entry into api programming... so actionhero. A generic Chapter on the github page or documentation about what to do/consider when updating actionhero packages would help.

Keep up the awesome work. If you are curious I am programming a "datacentral" for library data starting with german universities. Opensource actionhero with cluster capabilities could really be something here. So thx.

**Comment by evantahler** [comment]
Cool! Please share what you've made once it's up and running!
