### ISSUE TITLE
redis initializers Error: Callback was already called

### ISSUE THREAD

**Issue by tienne** [evantahler/actionhero#917]
Error: Callback was already called

- ActionHero Version: `15.0.0`
- Node.js Version: `4.4.5`
- Operating System `(Windows 10)`

Sometimes after my Actionhero server start error this exit node

```
Error: Callback was already called. at myproject\\node_modules\\actionhero\\node_modules\\async\\dist\\async.js:844:36
at myproject\\node_modules\\actionhero\\node_modules\\async\\dist\\async.js:3676:17
at myproject\\node_modules\\actionhero\\node_modules\\async\\dist\\async.js:339:31
at Redis.<anonymous> (myproject\\node_modules\\actionhero\\initializers\\redis.js:32:15
    at emitOne (events.js:82:20
    at Redis.emit (events.js:169:7
    at nextTickCallbackWith0Args (node.js:420:9
    at process._tickDomainCallback (node.js:390:13)
```

How can this problem, ask what advice

hero my  config/redis.js

```
var host     = process.env.REDIS_HOST;
var port     = process.env.REDIS_PORT;
var db = process.env.REDIS_DB;
var password = process.env.REDIS_PASS;

exports['default'] = {
  redis: function(api){
    
    if(process.env.FAKEREDIS === 'false' || process.env.REDIS_HOST !== undefined){
      return {
        '_toExpand': false,
        client: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        subscriber: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        tasks: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        }
      };
    }else {
      return {
        '_toExpand': false,
        client: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        subscriber: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        tasks: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        }
      };
    }
  }
};
```

**Comment by evantahler** [comment]
Great catch! 
I assume you are connecting to a real redis server.  If your connection is spotty (and you reconnect), that double-callback can happen.  We are detecting it and stoping the server to prevent anything bad from happening.

[This commit will handle this case properly](https://github.com/evantahler/actionhero/commit/a83187ac6d47622271141e492b7a06ad931c0210).  I'll release a new version of ActionHero today with the fix.

**Comment by evantahler** [comment]
https://github.com/evantahler/actionhero/releases/tag/v15.0.1 released on NPM. 
Thanks!

**Comment by tienne** [comment]
oh Thank you
i'm testing~

**Comment by tienne** [comment]
this issue close thank you
