### ISSUE TITLE
Stopping AH In Initializer's `start()`

### ISSUE THREAD

**Issue by paulxtiseo** [evantahler/actionhero#927]
Calling `api.commands.ctop()` in the `start()` of an initializer seems to result in an error:
```
C:\Repositories\Node\agent\node_modules\actionhero\actionhero.js:270
  if(self.api.running === true){
             ^

TypeError: Cannot read property 'running' of undefined
    at Object.actionhero.stop (C:\Repositories\Node\agent\node_modules\actionhero\actionhero.js:270:14)
    at C:\Repositories\Node\agent\initializers\1010_taskScheduler.js:25:24
    at arrayEach (C:\Repositories\Node\agent\node_modules\lodash\lodash.js:522:11)
    at Function.forEach (C:\Repositories\Node\agent\node_modules\lodash\lodash.js:9011:14)
    at Object.module.exports.start (C:\Repositories\Node\agent\initializers\1010_taskScheduler.js:16:7)
    at startFunction (C:\Repositories\Node\agent\node_modules\actionhero\actionhero.js:160:44)
    at C:\Repositories\Node\agent\node_modules\async\dist\async.js:3671:13
    at replenish (C:\Repositories\Node\agent\node_modules\async\dist\async.js:884:21)
    at iterateeCallback (C:\Repositories\Node\agent\node_modules\async\dist\async.js:869:21)
    at C:\Repositories\Node\agent\node_modules\async\dist\async.js:847:20
```

**Comment by evantahler** [comment]
Typo 'ctop'?

**Comment by paulxtiseo** [comment]
Oops, yes.

**Comment by evantahler** [comment]
Can you share your initializer? Any promises or re-assignment of "this"?

**Comment by paulxtiseo** [comment]
Here's the initializer in question. The error is triggered by passing a poorly-formatted task.schedule to the parser in line 20. 
```
'use strict';
var _ = require('lodash');
var ruleStringParser = require('rrule').rrulestr; 

module.exports = {
  loadPriority:  1010,
  startPriority: 1010,
  stopPriority:  1010,

  initialize: function(api, next) {
    next();
  },

  start: function(api, next) {

    _.forEach(api.config.agent.tasks, function(task) {
      if(task.active != false && (typeof task.schedule === "string")) {
        var schedule;
        try {
          schedule = new ruleStringParser(task.schedule);
          api.log('fileSynchronizer.schedule: ' + schedule.all(), 'info');
          //api.tasks.enqueue('fileSynchronizer', null, 'default');
        }
        catch(e) {
          api.log('Could not parse schedule for ' + task.name + '. Agent will stop.', 'error', task.schedule);
          api.commands.stop();
        }
      }
    });
    
    next();
  },

  stop: function(api, next) {
    next();
  }
};
```

**Comment by evantahler** [comment]
@paulxtiseo if you look at how this is used in the rest of ActionHero, it seems that we've always expected you to pass in a scope arguments.  

However, that is dumb. We can fix it like this: https://github.com/evantahler/actionhero/pull/928
