### ISSUE TITLE
EventEmitter memory leak detected 

### ISSUE THREAD

**Issue by tienne** [evantahler/actionhero#935]
# Name of Issue
Description of Issue

somtimes error EventEmitter memory leak detected

- ActionHero Version: `15.0.2`
- Node.js Version: `4.5.0`
- Operating System `Windows 10`

somtimes my actionhero server error EventEmitter memory leak detected
setMaxListeners is When should best Run?

here error log

```
2016-09-02T07:06:25.672Z - info: worker: started workerId=2
2016-09-02T07:06:26.186Z - info: worker: ended workerId=2
(node) warning: possible EventEmitter memory leak detected. 19 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Redis.addListener (events.js:239:17)
    at connection.connect (myproject\node_modules\node-resque\lib\connection.js:86:14)
    at queue.connect (myproject\node_modules\node-resque\lib\queue.js:25:19)
    at worker.connect (myproject\node_modules\node-resque\lib\worker.js:54:20)
    at multiWorker.startWorker (myproject\node_modules\node-resque\lib\multiWorker.js:67:10)
    at Immediate._onImmediate (myproject\node_modules\node-resque\lib\multiWorker.js:165:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-09-02T07:06:25.672Z - info: worker: started workerId=2
2016-09-02T07:06:26.186Z - info: worker: ended workerId=2
```

**Comment by evantahler** [comment]
Can you share more of the log before this snippet?  I'm going to imagine that you have developer mode enabled, and this happens after a reboot of the server?

**Comment by evantahler** [comment]
Using the following task (which is guaranteed to create and remove a multiWorker),  I am able reproduce this error.

```js
// task
'use strict';
var async = require('async');

exports.task = {
  name:          'looper',
  description:   'My Task',
  frequency:     0,
  queue:         'default',
  middleware:    [],

  run: function(api, params, next){
    var jobs = [];

    jobs.push(function(done){
      var i = 0;
      while(i < 999999999){
        i++;
      }

      done();
    });

    jobs.push(function(done){
      api.tasks.enqueueIn(1001, 'looper', {}, 'default', done);
    });

    async.series(jobs, next);
  }
};
```

Which yields:

```
...
192.168.7.25 @ 2016-09-02T15:21:24.367Z - info: worker: ended workerId=2
192.168.7.25 @ 2016-09-02T15:21:26.288Z - info: worker: job success default workerId=1, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:27.344Z - info: worker: started workerId=2
192.168.7.25 @ 2016-09-02T15:21:27.820Z - info: worker: job success default workerId=2, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:27.845Z - info: worker: ended workerId=2
192.168.7.25 @ 2016-09-02T15:21:30.778Z - info: worker: job success default workerId=1, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:31.830Z - info: worker: started workerId=2
192.168.7.25 @ 2016-09-02T15:21:32.301Z - info: worker: job success default workerId=2, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:32.333Z - info: worker: ended workerId=2
192.168.7.25 @ 2016-09-02T15:21:34.231Z - info: worker: job success default workerId=1, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
(node) warning: possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Redis.addListener (events.js:239:17)
    at connection.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/connection.js:86:14)
    at queue.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/queue.js:25:19)
    at worker.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/worker.js:54:20)
    at multiWorker.startWorker (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/multiWorker.js:67:10)
    at Immediate._onImmediate (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/multiWorker.js:165:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
192.168.7.25 @ 2016-09-02T15:21:35.293Z - info: worker: started workerId=2
192.168.7.25 @ 2016-09-02T15:21:35.761Z - info: worker: job success default workerId=2, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:35.796Z - info: worker: ended workerId=2
192.168.7.25 @ 2016-09-02T15:21:38.703Z - info: worker: job success default workerId=1, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
192.168.7.25 @ 2016-09-02T15:21:41.172Z - info: worker: job success default workerId=1, class=looper, queue=default, result=[undefined, 0=undefined, 1=1, 2=1, 3=1]
(node) warning: possible EventEmitter memory leak detected. 21 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Redis.addListener (events.js:239:17)
    at connection.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/connection.js:90:14)
    at queue.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/queue.js:25:19)
    at worker.connect (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/worker.js:54:20)
    at multiWorker.startWorker (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/multiWorker.js:67:10)
    at Immediate._onImmediate (/Users/evan/PROJECTS/actionhero/node_modules/node-resque/lib/multiWorker.js:165:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by evantahler** [comment]
This is actually in issue with `node-resque`.  Issue created =>  https://github.com/taskrabbit/node-resque/issues/155

**Comment by evantahler** [comment]
`node-resque` v3.0.3 is published, which fixes this issue.  Thanks for catching it!

https://github.com/taskrabbit/node-resque/releases/tag/v3.0.3

**Comment by tienne** [comment]
I'm sorry now that I 've seen
But node-resque is not include dependencies in my project package.json
what will be fixed inactionhero package.json dependencies?
Or will I need to be modified in myproject package.json

**Comment by evantahler** [comment]
`node-resque` is a dependency of ActionHero.  You can run `npm update` and it should also check the versions of dependent package's dependancies.

**Comment by tienne** [comment]
[@evantahler] thank you~
